// app/(routes)/(tools)/chat/components/Input.tsx
'use client';

import React, {useRef, useState} from 'react';
import {Button, TextareaAutosize} from '@mui/material';
import {useSearchParams} from "next/navigation";

const InputComponent: React.FC = () => {
    const searchParams = useSearchParams();
    const messageRef = useRef<any>();
    const [chatValue, setChatValue] = useState<string>('');
    const [isDisabled, setIsDisabled] = useState<boolean>(false);

    const sessionId = searchParams.get("sessionId");

    const onSendMsg = async (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            await sendMessage();
        }
    };

    const sendMessage = async () => {
        if (isDisabled) return;
        try {
            let text = chatValue;
            if (text === '' || /^\s+$/.test(text)) {
                // message.warn('Input your question');
                return;
            }
            setIsDisabled(true);
            const payload = {
                sessionId: sessionId,
                prompt: chatValue,
            };
            // await chatStore.sendMessage(payload);
            // await sessionStore.getSessionList();
            setChatValue('');
        } catch (error) {
            console.warn('[ sendMessage error ]', error);
        } finally {
            setIsDisabled(false);
        }
    };

    return (
        <div
            className="input-component absolute bottom-0 z-9 pt-5 pb-10 bg-white flex w-full">
            <form
                className="mx-auto flex gap-3 bg-[var(--ant-primary-color-3)] py-[10px] px-4 border border-black/10 rounded-xl shadow-sm w-[70%]"
                onSubmit={(e) => e.preventDefault()}
            >
                <TextareaAutosize
                    className="textarea m-0 w-full resize-none p-0 focus:ring-0 focus-visible:ring-0 md:pr-2 pl-3 md:pl-0 text-base placeholder:text-[#666] border-none"
                    maxLength={2000}
                    minRows={2}
                    maxRows={8}
                    value={chatValue}
                    placeholder="Please enter your question here..."
                    onKeyDown={onSendMsg}
                    onChange={(e: any) => setChatValue(e.target.value)}
                />
                <Button
                    variant="contained"
                    color="primary"
                    size="large"
                    className="rounded-lg"
                    onClick={sendMessage}
                    disabled={isDisabled || !chatValue}
                >
                    SEND
                </Button>
            </form>
        </div>
    );
};

export default InputComponent;

// components/InputComponent.vue
<template>
  <div class="input-component absolute bottom-0 left-0 right-0 z-9 py-3.5 bg-gradient-to-b bg-white bg-opacity-80">
    <a-form
        class="stretch mx-2 flex flex-row gap-3 last:mb-2 md:mx-4 md:last:mb-6 lg:mx-auto lg:max-w-2xl xl:max-w-5xl">
      <div
          class="bg-[var(--ant-primary-color-3)] flex w-full py-[10px] flex-grow px-4 relative border border-black/10 rounded-xl shadow-sm">
        <a-textarea
            ref="messageRef"
            class="textarea m-0 w-full resize-none p-0 focus:ring-0 focus-visible:ring-0 md:pr-2 pl-3 md:pl-0 text-base placeholder:text-[#666]"
            :bordered="false"
            :maxlength="2000"
            :show-count="true"
            :auto-size="{ minRows: 2, maxRows: 8 }" v-model:value="state.chatValue"
            placeholder="Please enter your question here..."
            @keydown="onSendMsg"/>
        <a-button type="primary"
                  size="large"
                  class="rounded-lg"
                  native-type="submit"
                  @click="sendMessage"
                  :disabled="state.isDisabled || !state.chatValue">
          SNED
          <send-outlined/>
        </a-button>
      </div>
    </a-form>
  </div>
</template>
<script setup>
import {reactive} from 'vue'
import {SendOutlined} from '@ant-design/icons-vue'
import {message} from "ant-design-vue";
import {useChatStore} from "~/store";

const route = useRoute()
const chatStore = useChatStore()
const state = reactive({
  sessionId: computed(() => route.query.sessionId),
  chatValue: '',
  isDisabled: false
})

const sendMessage = async () => {
  if (state.isDisabled) return
  try {
    let text = state.chatValue
    if (text === '' || /^\s+$/.test(text)) {
      message.warn('Input your question')
      return
    }
    state.isDisabled = true
    const payload = {
      sessionId: state.sessionId,
      prompt: state.chatValue,
    }
    await chatStore.sendMessage(payload)
  } catch (error) {
    console.warn('[ sendMessage error ]', error)
  } finally {
    state.isDisabled = false
  }
}

const onSendMsg = (e) => {
  if (e.keyCode === 13 && !e.shiftKey) {
    e.preventDefault()
    sendMessage()
  }
}
</script>
<style scoped lang="less">
.textarea {
  background-color: transparent;

  &:focus {
    outline: 0;
    box-shadow: none;
  }

  textarea {
    font-size: 16px;
  }
}

.ant-input-textarea-show-count {
  &::after {
    position: absolute;
    right: 16px;
    bottom: 0;
    font-size: 14px;
  }
}
</style>
<style lang="less">
.input-component {
  textarea {
    font-size: 16px;
  }
}
</style>
